version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5050:5050'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    restart: always

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
